# Create a 1D NumPy array of numbers from 0 to 9.	


In [2]:

import numpy as np

In [3]:
a1 = np.arange (10)
print(a1)


[0 1 2 3 4 5 6 7 8 9]


# Create a 2D array of shape (3, 3) with all elements as 1.	


In [4]:
a1 = np.ones((3,3))
print (a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3. Generate a NumPy array of 15 random integers between 10 and 50

In [8]:
arr3 = np.random.randint(10, 51, size=15)


In [9]:
arr3 

array([18, 33, 42, 44, 28, 49, 48, 42, 13, 48, 35, 26, 15, 16, 27],
      dtype=int32)

## 4. Create an array of 5 evenly spaced numbers between 0 and 1 (inclusive)

In [32]:
arr4 = np.linspace(0, 1 ,5)
arr4

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 5. Create a 4x4 identity matrix using NumPy

In [30]:
identity_matrix = np.eye(4)
identity_matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 6. Create an array from the list [10, 20, 30, 40] and change the data type to float


In [13]:
arr5 = np.array([10, 20, 30, 40], dtype=float)
arr5

array([10., 20., 30., 40.])

## 7. Create a 3x3 array with values from 1 to 9, then extract the second column

In [20]:
arr6 = np.arange(1, 10).reshape((3, 3))
second_column= arr6[:, 1]
second_column

array([2, 5, 8])

## 8. Create a 1D array with 10 elements and reshape it into a 2x5 matrix


In [17]:

arr7 = np.arange(10).reshape((2, 5))
arr7


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 9. Create two 2x2 matrices and perform matrix multiplication


In [19]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(mat1, mat2)
matrix_product 

array([[19, 22],
       [43, 50]])

## 10. Given the array arr = np.array([5, 12, 7, 18, 3]), replace all values greater than 10 with 100


In [26]:
arr8 = np.array([5, 12, 7, 18, 3])
arr8[arr8 > 10]= 100
arr8

array([  5, 100,   7, 100,   3])